[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_YARN = "false"
  YARN_VERSION = "0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Ensure all styles are included in deployment
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle redirects for authentication
[[redirects]]
  from = "/auth/*"
  to = "/auth/[...slug].html"
  status = 200
  status = 200

# Handle Next.js rewrites
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
