[build]
  command = "npm ci --legacy-peer-deps || npm install --legacy-peer-deps --force && node install-components.js && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Handle redirects for authentication
[[redirects]]
  from = "/auth/*"
  to = "/auth/[...slug].html"
  status = 200

# Handle API routes correctly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true
  
# Important: Set your environment variables in the Netlify dashboard
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
# SITE_URL

# Handle Next.js rewrites
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
